const env = {
    SERVER_URL: 'https://qa-backend-hxbh.onrender.com/',
    QS_MAIN: [
        {
          title: 'Question 1',
          question: 'I know that different search engines may give different search results, because they are influenced by commercial factors.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 2',
          question: 'I know which words to use in order to find what I need quickly (e.g. to search online or within a document).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 3',
          question: 'When I use a search engine, I can take advantage of its advanced features.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 4',
          question: 'I know how to find a website I have visited before.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 5',
          question: 'I know how to differentiate promoted content from other content I find or receive online (e.g., recognizing an advert on social media or search engines).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 6',
          question: 'I know how to identify the purpose of an online information source (e.g., to inform, influence, entertain, or sell).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 7',
          question: 'I critically check if the information I find online is reliable.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 8',
          question: 'I know that some information on the Internet is false (e.g., fake news).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 9',
          question: 'I know about different storage media (e.g., internal or external hard disk, USB memory, pen drive, memory card).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 10',
          question: 'I know how to organize digital content (e.g., documents, images, videos) using folders or tagging to find them back later.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 11',
          question: 'I know how to copy and move files (e.g., documents, images, videos) between folders, devices, or on the cloud.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 12',
          question: 'I know how to manage and analyze data using software (e.g., sorting, filtering, and creating charts).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 13',
          question: 'I know how to protect devices and personal data (e.g., using antivirus, strong passwords, and backups).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 14',
          question: 'I know how to avoid and report harmful or inappropriate online content.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 15',
          question: 'I know how to protect myself from online scams and phishing.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 16',
          question: 'I know how to use privacy settings on social networks to control who can see what I share.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 17',
          question: 'I know how to use different tools to collaborate online (e.g., shared documents, virtual meetings).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 18',
          question: 'I know how to participate in social networks and online communities responsibly and respectfully.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 19',
          question: 'I know how to create and share digital content (e.g., text, images, videos).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 20',
          question: 'I know how to use digital tools to support my learning (e.g., educational apps, online courses).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 21',
          question: 'I know how to apply for a job using a digital platform (e.g., filling a form, uploading my CV and photo).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 22',
          question: 'I know that many public services are available on the Internet (e.g., booking a health visit, submitting tax declaration, requesting birth, marriage, residence and other certificates).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 23',
          question: 'I know how to pay for goods and services that I buy online (e.g., using direct bank transfer, credit/debit cards, other online payment systems).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 24',
          question: 'It matters to me to debate social or political issues online (e.g., in online forums, news sites, Facebook, Twitter).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 25',
          question: 'I understand the benefits of remote collaboration (e.g., reduced commuting time).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 26',
          question: 'I know how to edit a shared, online document.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 27',
          question: 'I know how to invite others and give appropriate permissions to collaborate on a shared document.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 28',
          question: 'I am aware that I should ask permission from a person before publishing or sharing photos about them.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 29',
          question: 'I know how to recognize online messages and behaviors that attack certain groups or individuals (e.g., hate speech).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 30',
          question: 'I can take the right measures if someone is doing the wrong thing online (e.g., an offensive comment, threats).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 31',
          question: 'I know how to create strong passwords to protect my online accounts.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 32',
          question: 'I know how to use software to keep my computer secure (e.g., antivirus, firewall).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 33',
          question: 'I know how to avoid and report spam and phishing emails.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 34',
          question: 'I know how to use privacy settings on social networks to protect my personal information.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 35',
          question: 'I know how to protect my personal information when using public Wi-Fi.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 36',
          question: 'I know how to back up important data to avoid losing it.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 37',
          question: 'I know how to use two-factor authentication to add an extra layer of security to my online accounts.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 38',
          question: 'I know how to use encryption tools to protect sensitive information.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 39',
          question: 'I know how to manage and update my online accounts to keep them secure.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 40',
          question: 'I know how to recognize and avoid malware and viruses when browsing the internet.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 41',
          question: 'I know how to configure my browser to enhance security and privacy (e.g., disabling cookies, using incognito mode).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 42',
          question: 'I know how to use a password manager to create and store strong passwords.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 43',
          question: 'I know how to identify and avoid online scams (e.g., fake websites, fraudulent offers).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 44',
          question: 'I know how to secure my home network (e.g., setting a strong password for Wi-Fi, using a firewall).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 45',
          question: 'I know how to report online fraud to the relevant authorities.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 46',
          question: 'I know how to stay informed about the latest cybersecurity threats and how to protect against them.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 47',
          question: 'I know how to protect my personal data when using online services and apps.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 48',
          question: 'I know how to create secure backup copies of important documents and files.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 49',
          question: 'I know how to use parental control tools to protect children from harmful online content.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
        {
          title: 'Question 50',
          question: 'I know how to use secure communication tools (e.g., encrypted messaging apps) to protect my privacy.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
        },
      ]
}

export default env