const env = {
    SERVER_URL: 'http://qa-backend-hxbh.onrender.com/e-learning-portal/api/core/v01',

    // 'https://qa-backend-hxbh.onrender.com/e-learning-portal/api/core/v01'

    QS_MAIN: [
        {
          title: 'Question 1',
          question: 'I know that different search engines may give different search results, because they are influenced by commercial factors.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Intermediate',
        },
        {
          title: 'Question 2',
          question: 'I know which words to use in order to find what I need quickly (e.g. to search online or within a document).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Foundation',
        },
        {
          title: 'Question 3',
          question: 'When I use a search engine, I can take advantage of its advanced features.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 4',
          question: 'I know how to find a website I have visited before.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Foundation',
        },
        {
          title: 'Question 5',
          question: 'I know how to differentiate promoted content from other content I find or receive online (e.g., recognizing an advert on social media or search engines).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Intermediate',
        },
        {
          title: 'Question 6',
          question: 'I know how to identify the purpose of an online information source (e.g., to inform, influence, entertain, or sell).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Intermediate',
        },
        {
          title: 'Question 7',
          question: 'I critically check if the information I find online is reliable.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 8',
          question: 'I know that some information on the Internet is false (e.g., fake news).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 9',
          question: 'I know about different storage media (e.g., internal or external hard disk, USB memory, pen drive, memory card).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 10',
          question: 'I know how to organize digital content (e.g., documents, images, videos) using folders or tagging to find them back later.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Foundation',
        },
        {
          title: 'Question 11',
          question: 'I know how to copy and move files (e.g., documents, images, videos) between folders, devices, or on the cloud.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Foundation',
        },
        {
          title: 'Question 12',
          question: 'I know how to manage and analyze data using software (e.g., sorting, filtering, and creating charts).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 13',
          question: 'I know how to protect devices and personal data (e.g., using antivirus, strong passwords, and backups).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 14',
          question: 'I know how to avoid and report harmful or inappropriate online content.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 15',
          question: 'I know how to protect myself from online scams and phishing.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 16',
          question: 'I know how to use privacy settings on social networks to control who can see what I share.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 17',
          question: 'I know how to use different tools to collaborate online (e.g., shared documents, virtual meetings).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 18',
          question: 'I know how to participate in social networks and online communities responsibly and respectfully.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 19',
          question: 'I know how to create and share digital content (e.g., text, images, videos).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 20',
          question: 'I know how to use digital tools to support my learning (e.g., educational apps, online courses).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 21',
          question: 'I know how to apply for a job using a digital platform (e.g., filling a form, uploading my CV and photo).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 22',
          question: 'I know that many public services are available on the Internet (e.g., booking a health visit, submitting tax declaration, requesting birth, marriage, residence and other certificates).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 23',
          question: 'I know how to pay for goods and services that I buy online (e.g., using direct bank transfer, credit/debit cards, other online payment systems).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Foundation',
        },
        {
          title: 'Question 24',
          question: 'It matters to me to debate social or political issues online (e.g., in online forums, news sites, Facebook, Twitter).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 25',
          question: 'I understand the benefits of remote collaboration (e.g., reduced commuting time).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 26',
          question: 'I know how to edit a shared, online document.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 27',
          question: 'I know how to create a digital content collaboratively.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 28',
          question: 'I know that the digital content (text, images, videos, music) that I find online are covered by copyrights and licenses.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 29',
          question: 'I know how to protect my digital content (e.g., using watermarks, appropriate licenses).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 30',
          question: 'I always respect copyrights and licenses of digital content.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 31',
          question: 'I make sure that the information I share with others is accurate and reliable.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 32',
          question: 'I know that I need to keep my personal and professional digital profiles separate (e.g., social media, emails).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Intermediate',
        },
        {
          title: 'Question 33',
          question: 'I know how to differentiate between a professional and a personal social network profile (e.g., what kind of information is appropriate to share and with whom).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Intermediate',
        },
        {
          title: 'Question 34',
          question: 'I understand that my digital footprint is part of my online identity.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 35',
          question: 'I know how to create an appropriate online identity (e.g., through professional networking sites).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 36',
          question: 'I know how to manage my digital footprint (e.g., ensuring that my digital actions are consistent with my professional and personal image).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 37',
          question: 'I know how to follow professional ethics and norms in online interactions (e.g., respecting the privacy and confidentiality of clients).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 38',
          question: 'I understand that the digital technologies I use have an environmental impact.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 39',
          question: 'I make an effort to minimize the environmental impact of my digital activities (e.g., using energy-efficient devices, recycling electronic waste).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 40',
          question: 'I know how to maintain a balanced and healthy digital lifestyle (e.g., setting limits on screen time, taking breaks).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 41',
          question: 'I know that digital technologies can be addictive and can negatively affect my well-being.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 42',
          question: 'I know how to stay safe online (e.g., recognizing and avoiding potential threats such as cyberbullying and online harassment).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 43',
          question: 'I understand the importance of digital well-being and try to promote it in my community (e.g., through awareness campaigns, digital detox events).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 44',
          question: 'I am careful to follow the rules about copyrights and licenses of digital content that I find.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 45',
          question: 'I make sure that the information I share with others is accurate and reliable.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Attitude',
          level: 'Intermediate',
        },
        {
          title: 'Question 46',
          question: 'I know that the digital content (text, images, videos, music) that I create is covered by copyrights and licenses.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Foundation',
        },
        {
          title: 'Question 47',
          question: 'I know how to protect my digital content (e.g., using watermarks, appropriate licenses).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 48',
          question: 'I know how to use software to create and edit digital content (e.g., text, images, videos).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 49',
          question: 'I know how to share digital content responsibly (e.g., ensuring that I have the right to share it and that it is appropriate for the audience).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Intermediate',
        },
        {
          title: 'Question 50',
          question: 'I can write scripts, macros and simple applications to automate the execution of a task.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 51',
          question: 'I can design and develop a website or an app.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 52',
          question: 'I know how to use data analytics tools to analyze and interpret data (e.g., spreadsheets, data visualization software).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 53',
          question: 'I know how to use project management software to plan, execute, and monitor projects (e.g., tracking progress, managing resources).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 54',
          question: 'I can set up and configure a computer network.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 55',
          question: 'I know how to troubleshoot and solve common technical issues with digital devices and software.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 56',
          question: 'I know how to develop and implement cybersecurity measures to protect digital systems and data.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 57',
          question: 'I understand the principles of digital transformation and its impact on business and society.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Knowledge',
          level: 'Advanced',
        },
        {
          title: 'Question 58',
          question: 'I can develop a digital strategy to support business goals and objectives.',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 59',
          question: 'I know how to manage digital change and transformation within an organization (e.g., leading a digital transformation project).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 60',
          question: 'I can use digital tools and technologies to drive innovation within an organization (e.g., developing new products or services).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 61',
          question: 'I know how to integrate digital tools and technologies into existing business processes (e.g., automating workflows, improving efficiency).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 62',
          question: 'I know how to manage and analyze large datasets (e.g., using big data technologies, machine learning).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 63',
          question: 'I know how to develop and implement a digital marketing strategy (e.g., using social media, SEO, email marketing).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 64',
          question: 'I know how to use digital tools to support customer engagement and relationship management (e.g., CRM software).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 65',
          question: 'I can develop and implement a digital content strategy (e.g., creating and distributing valuable, relevant content).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 66',
          question: 'I know how to use digital tools and technologies to support decision-making (e.g., business intelligence software, data analytics).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 67',
          question: 'I know how to use digital tools and technologies to support collaboration and teamwork (e.g., project management software, communication tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 68',
          question: 'I can develop and implement a digital communication strategy (e.g., using digital channels to communicate with stakeholders).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 69',
          question: 'I know how to use digital tools and technologies to support learning and development (e.g., e-learning platforms, online courses).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 70',
          question: 'I know how to manage and analyze social media data (e.g., using social media analytics tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 71',
          question: 'I can develop and implement a digital sales strategy (e.g., using e-commerce platforms, online sales channels).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 72',
          question: 'I know how to use digital tools and technologies to support human resource management (e.g., HR software, online recruitment tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 73',
          question: 'I can develop and implement a digital innovation strategy (e.g., using digital tools to create new products or services).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 74',
          question: 'I know how to use digital tools and technologies to support supply chain management (e.g., inventory management software, logistics tracking tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 75',
          question: 'I can develop and implement a digital transformation strategy (e.g., integrating digital tools into business processes, driving digital change).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 76',
          question: 'I know how to use digital tools and technologies to support financial management (e.g., accounting software, financial planning tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 77',
          question: 'I can develop and implement a digital customer service strategy (e.g., using chatbots, online support tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 78',
          question: 'I know how to use digital tools and technologies to support product development (e.g., CAD software, 3D printing tools).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 79',
          question: 'I can develop and implement a digital workplace strategy (e.g., using digital tools to support remote work, collaboration).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
        {
          title: 'Question 80',
          question: 'I know how to use digital tools and technologies to support business continuity (e.g., disaster recovery planning, backup systems).',
          options: ['No knowledge', 'Limited understanding', 'Good understanding', 'Fully master'],
          answer: '',
          points: 0,
          type: 'Skills',
          level: 'Advanced',
        },
      ]
}

export default env